name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Chạy khi bạn push code lên branch main

permissions:
  contents: write # Cực kỳ quan trọng: Cấp quyền cho robot tạo và ghi vào branch gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Deploy sang branch gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: Frontend_design
          branch: gh-pages # Tự động tạo và đẩy code sang branch này